.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ring_qt test_ring_qt
clean: FORCE
	$(MAKE) -C .. ring_qt_clean test_ring_qt_clean
check: FORCE
	$(MAKE) -C .. test_ring_qt_check
ring-qt ring-qt.exe: FORCE
	 $(MAKE) -C .. ring_qt
